### PR TITLE
contributing name change

### PR DESCRIPTION
**Pull request by KrystalOm**
still confusing..

### CODE REVIEW

**Review by ardal-akbar — DISMISSED** [review]

**Review by HuiYang37 — DISMISSED** [review]
Looks good

**Review by Karma336 — DISMISSED** [review]

**Review by HuiYang37 — DISMISSED** [review]
Good

**Review by Xiaoligithub168 — DISMISSED** [review]
Great job!

**Comment by ITgirlLL** [comment]
You have to resolve conflicts before approving and merging.

**Review by HuiYang37 — APPROVED** [review]
Good to go.

**Review by ardal-akbar — APPROVED** [review]
Looks good now.

**Review by ITgirlLL — APPROVED** [review]

**Pull request merged**
