### PR TITLE
Sarah's name added

### PR DESCRIPTION
**Pull request by ShaolingStouder**

### CODE REVIEW

**Review by HuiYang37 — DISMISSED** [review]
Good

**Review by ardal-akbar — DISMISSED** [review]
Looks Good!

**Review by Tsai-Anthony — APPROVED** [review]
looks good! time to merge!

**Review by Tsai-Anthony — CHANGES_REQUESTED** [review]
the master branch has been updated, which creates a conflict in your current file. Please update the new list of names and add your name again.

**Review by HuiYang37 — CHANGES_REQUESTED** [review]
NO!!! Please don't delete someone else's name. When try to resolve THIS conflict, keep both your name and the name you have conflict with.

**Comment by ShaolingStouder** [comment]
> NO!!! Please don't delete someone else's name. When try to resolve THIS conflict, keep both your name and the name you have conflict with.

hi please take a look again. Thanks

**Comment by ShaolingStouder** [comment]
> the master branch has been updated, which creates a conflict in your current file. Please update the new list of names and add your name again.

hello I push up again. take a look plz

**Comment by HuiYang37** [comment]
> > the master branch has been updated, which creates a conflict in your current file. Please update the new list of names and add your name again.
> 
> hello I push up again. take a look plz

Nothing wrong with your codes, but you "attempt" modify the same line as Minh did. So don't push. Instead, go to pull request, at very bottom, there's a button called "resolve conflict". Click it. It will bring up conflict resolution menu. It will show somethng like this:
<<<<<<<your_branch_name<<<<<
incoming change
===============
keep change
>>>>>>master>>>>>>>

you have a choice to make, do you wan to keep either or both (HUGE HINT)?
If you do, keep the codes you want, delete <<<, >>>, and ===. Then submit. 
Once again, nothing wrong with your codes. You just need to resolve the conflict.

**Comment by HuiYang37** [comment]
Nothing wrong with your codes, but you "attempt" modify the same line as Minh did. So don't push. Instead, go to pull request, at very bottom, there's a button called "resolve conflict". Click it. It will bring up conflict resolution menu. It will show somethng like this:
<<<<<<<<your_branch_name<<<<<
incoming change
\===========
keep change
\>>>>>>>>>master>>>>>

you have a choice to make, do you wan to keep either or both (HUGE HINT)?
If you do, keep the codes you want, delete <<<, >>>, and ===. Then submit. 
Once again, nothing wrong with your codes. You just need to resolve the conflict.

**Review by HuiYang37 — CHANGES_REQUESTED** [review]
Please resolve the conflict.

**Review by ardal-akbar — APPROVED** [review]
Now it is good. Once you get enough approve we can merge.

**Review by HuiYang37 — APPROVED** [review]
It looks good.

**Review by murad-boratech — APPROVED** [review]

**Pull request closed without merging**
