### PR TITLE
PR-hui Added hui.txt

### PR DESCRIPTION
**Pull request by HuiYang37**
Created hui.txt, added "Hello, Hui"

### CODE REVIEW

**Review by Tsai-Anthony — APPROVED** [review]
nice work

**Review by KrystalOm — APPROVED** [review]
good job!

**Review by ITgirlLL — APPROVED** [review]

**Review by KrystalOm — COMMENTED** [review]
perfect!

**Review by Karma336 — COMMENTED** [review]
i don't see approve review button but I can see submit review button and I am clicking on it..

**Review by MarvLopez — COMMENTED** [review]
LGTM!

**Pull request merged**
