### PR TITLE
[PR-1] contributors edited

### PR DESCRIPTION
**Pull request by helen-ahn**
PR from my new branch:)
It seems like I can't remove murad from the reviewers list..?

### CODE REVIEW

**Review by aliceoh324 — DISMISSED** [review]
yay!

**Review by HuiYang37 — DISMISSED** [review]
Looks good

**Review by ardal-akbar — DISMISSED** [review]
Great!

**Review by ardal-akbar — APPROVED** [review]

**Review by Karma336 — APPROVED** [review]

**Review by ardal-akbar — APPROVED** [review]
:)

**Review by ardal-akbar — APPROVED** [review]
:)

**Review by HuiYang37 — APPROVED** [review]
Looks good

**Comment by HuiYang37** [comment]
Yours is ready to merge.

**Pull request merged**
