### PR TITLE
updated karma-2 [01]

### PR DESCRIPTION
**Pull request by Karma336**
please check my pr. Second time doing it. I didn't see my name earlier. Must have missed some steps..

### CODE REVIEW

**Review by KrystalOm — DISMISSED** [review]

**Review by Tsai-Anthony — CHANGES_REQUESTED** [review]
theres a conflict. you will need yo update all the new names from the main branch.

**Review by javi-lopezz — COMMENTED** [review]
Looks like you have to pull from the master again first and then add your name. To get the updated list

**Review by KrystalOm — CHANGES_REQUESTED** [review]
changes needed~~

**Review by ardal-akbar — DISMISSED** [review]
You have to either take care of the conflict in web editor in Github or cancel this pull request and try to pull from master branch again so you get the most updated contributers.txt file and request again.

**Comment by Karma336** [comment]
> Looks like you have to pull from the master again first and then add your name. To get the updated list

do i have to do it all over again....?

**Review by Tsai-Anthony — APPROVED** [review]
beautiful karma

**Review by KrystalOm — APPROVED** [review]
perfect!

**Comment by Karma336** [comment]
> beautiful karma

did it merge? i don't know..it says merging is blocked

**Review by aliceoh324 — APPROVED** [review]

**Comment by Tsai-Anthony** [comment]
> > beautiful karma
> 
> did it merge? i don't know..it says merging is blocked

you need at lease 1 code master and 2 people to approve. once you meet that then you can merge to the main/master branch

**Pull request merged**
