### PR TITLE
[PR] Alice_Homework0718

### PR DESCRIPTION
**Pull request by aliceoh324**
Am I doing this right...?

### CODE REVIEW

**Review by ardal-akbar — CHANGES_REQUESTED** [review]
Hello, Alice 
Instead of creating a new text file we are required to edit the contributers.txt file. Add your name under Murad's.

**Review by Karma336 — APPROVED** [review]

**Review by HuiYang37 — DISMISSED** [review]
you're good

**Review by Karma336 — DISMISSED** [review]

**Review by ardal-akbar — DISMISSED** [review]
Good now!

**Comment by ardal-akbar** [comment]
@aliceoh324  Now use this web editor to handle the conflict just like we did it on git. Make sure not delete Hui's name.

**Review by MarvLopez — DISMISSED** [review]

**Review by javi-lopezz — DISMISSED** [review]
LGTM

**Review by KrystalOm — DISMISSED** [review]
good job!

**Review by Tsai-Anthony — APPROVED** [review]
merge time

**Review by KrystalOm — APPROVED** [review]
good job!

**Review by Karma336 — APPROVED** [review]

**Pull request merged**
