### PR TITLE
I am done Alice_Homework0718 #30? Thanks bro.

### PR DESCRIPTION
**Pull request by Turhunjohn**
Could you please confirm my pull request for Alice_Homework0718 #30? Thanks bro.

### CODE REVIEW

**Review by Tsai-Anthony — CHANGES_REQUESTED** [review]
please pull from the main/master branch.
the current list of names at this time is
```
Contributer List:
 - Murad
 - Hui
 - Krystal
 - Lena
 - Helen
 - Lydia
 - Ardal
 - Javier
 - Anthony
 - Marvin
```
youll just need to add your name to that list

**Review by ardal-akbar — CHANGES_REQUESTED** [review]
The homework is to add your name in contributers.txt file along with all the names we already had in there. 
What you did here is you created a new text file which is not the requirment for homework.
Please apply changes as mentioned above and request to pull again, Thank you!

**Review by Minh999999 — APPROVED** [review]
lgtm!

**Comment by HuiYang37** [comment]
Please read the assignement carefully. You don't add any new file to the repo. You have do "git pull" in your local repo, then update the contributors.txt with the additional of your name, then "git push" in your local branch, finally make a pull request in GitHub to merge into the online master branch.

**Pull request closed without merging**
