### PR TITLE
[BT-17] name added

### PR DESCRIPTION
**Pull request by ITgirlLL**
Pull request. Thanks.

### CODE REVIEW

**Review by HuiYang37 — DISMISSED** [review]
Good.

**Review by Xiaoligithub168 — DISMISSED** [review]
Great!

**Review by ardal-akbar — DISMISSED** [review]

**Review by LenaChen7 — DISMISSED** [review]
looking good Lydia , :)

**Comment by HuiYang37** [comment]
Hey, Lydia, when you try to resolve the conflict, make sure you understand what's incoming change and what's keep change. You can't just delete both Helen and Hui name in the file and keep yours.

**Review by LenaChen7 — APPROVED** [review]
well done !!!!!!

**Review by KrystalOm — APPROVED** [review]
great job!

**Review by LenaChen7 — DISMISSED** [review]
hahahaha

**Review by HuiYang37 — DISMISSED** [review]
Now it looks good.

**Review by KrystalOm — DISMISSED** [review]
good job

**Review by Xiaoligithub168 — DISMISSED** [review]
Great job again!

**Comment by HuiYang37** [comment]
One more time, why is Murad name missing? You HAVE TO keep his name.

**Review by ardal-akbar — DISMISSED** [review]

**Review by ardal-akbar — APPROVED** [review]
Good job!

**Review by HuiYang37 — APPROVED** [review]
Looks good

**Review by KrystalOm — APPROVED** [review]
looks good~!

**Pull request merged**
