### PR TITLE
[BT-777] - greeting Initialization

### PR DESCRIPTION
**Pull request by LenaChen7**
initialize name : Lena.

### CODE REVIEW

**Review by MoeMo01 — APPROVED** [review]

**Review by Tsai-Anthony — APPROVED** [review]
nice

**Review by aliceoh324 — APPROVED** [review]
NICE!!

**Review by Xiaoligithub168 — APPROVED** [review]
great job!

**Review by KrystalOm — APPROVED** [review]
great job!

**Pull request merged**
