### PR TITLE
Homework 07/20

### PR DESCRIPTION
**Pull request by Tsai-Anthony**
image

### CODE REVIEW

**Review by ardal-akbar — DISMISSED** [review]
Looks Good!

**Comment by Tsai-Anthony** [comment]
SmoggyNiceBluet-max-1mb

**Review by KrystalOm — DISMISSED** [review]
good job!

**Comment by ardal-akbar** [comment]
Changes needed now!

**Review by javi-lopezz — DISMISSED** [review]
LGTM

**Review by ardal-akbar — APPROVED** [review]
We good!

**Review by javi-lopezz — APPROVED** [review]
LGTM

**Review by Karma336 — APPROVED** [review]

**Review by KrystalOm — APPROVED** [review]
super!

**Pull request merged**
