### PR TITLE
Name Addition - Add a name

### PR DESCRIPTION
**Pull request by LenaChen7**
Does homework like this?

### CODE REVIEW

**Comment by LenaChen7** [comment]
Approve me ?!?!!??!?! Please

**Review by HuiYang37 — DISMISSED** [review]
Looks good

**Review by Xiaoligithub168 — DISMISSED** [review]
Good Girl!

**Review by ITgirlLL — DISMISSED** [review]
You did the same like me. we should've removed Hui from the code first. lol

**Review by ardal-akbar — APPROVED** [review]

**Review by HuiYang37 — APPROVED** [review]
Good

**Review by ITgirlLL — APPROVED** [review]

**Pull request merged**
